version: '3.8'

services:
  django:
    build:
      context: .
      cache_from:
        - demodjango/application:latest
    image: demodjango/application:latest
    environment:
      ALLOWED_HOSTS: '*'
      AWS_ENDPOINT_URL: 'http://s3:9090'
      DATABASE_CREDENTIALS: '{"password":"pgSecretPassword","dbname":"main","engine":"postgres","port":5432,"dbInstanceIdentifier":"xxx","host":"postgres-aurora","username":"postgres"}'
      DEBUG: true
      DJANGO_SECRET_KEY: this_is_an_example_use_a_proper_key_in_production
      OPENSEARCH_ENDPOINT: 'http://opensearch:9200'
      RDS_DATABASE_CREDENTIALS: '{"password":"pgSecretPassword","dbname":"main","engine":"postgres","port":5432,"dbInstanceIdentifier":"xxx","host":"postgres-rds","username":"postgres"}'
      REDIS_ENDPOINT: 'redis://redis:6379'
      S3_BUCKET_NAME: test-bucket
      AWS_ACCESS_KEY_ID: access-key-id
      AWS_SECRET_ACCESS_KEY: secret-access-key
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel:4317'
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: 'http://otel:4317'
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    links:
      - postgres-rds
      - postgres-aurora
      - redis
      - s3
      - opensearch
      - otel

  otel:
    image: public.ecr.aws/aws-observability/aws-otel-collector:v0.17.0
    environment:
      AWS_REGION: eu-west-2

  celery-worker:
    image: demodjango/application:latest
    command: celery --app demodjango.celery worker --task-events --loglevel INFO
    entrypoint: ''
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      REDIS_ENDPOINT: redis://redis:6379
      DEBUG: true
      DJANGO_SECRET_KEY: this_is_an_example_use_a_proper_key_in_production
      DJANGO_SETTINGS_MODULE: demodjango.settings

  postgres-rds:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pgSecretPassword
      POSTGRES_DB: main

  postgres-aurora:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pgSecretPassword
      POSTGRES_DB: main

  redis:
    image: redis
    # Expose port so we can query it for debugging
    ports:
      - "6379:6379"

  s3:
    image: adobe/s3mock
    environment:
      initialBuckets: test-bucket

  opensearch:
    image: opensearchproject/opensearch
    environment:
      'discovery.type': single-node
      'plugins.security.disabled': true
