[tool.poetry]
name = "demodjango"
version = "0.1.0"
description = ""
authors = ["Will Gibson <8738245+WillGibson@users.noreply.github.com >"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

