[tool.poetry]
name = "demodjango"
# See git tags for versioning
version = "0.0.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.34.21"
celery = "^5.3.6"
dbt-copilot-python = "^0.1.4"
dj-database-url = "^2.1.0"
django = "^3.2.23"
django-environ = "^0.11.2"
django-ipware = "^3.0.7"
django-log-formatter-asim = "^0.0.4"
django-requestlogs = "^0.8"
elasticsearch = "^7.10.1"
gunicorn = "^21.2.0"
opentelemetry-distro = "^0.43b0"
opentelemetry-exporter-otlp = "^1.22.0"
opentelemetry-instrumentation-wsgi = "^0.43b0"
opentelemetry-propagator-aws-xray = "^1.0.1"
opentelemetry-sdk-extension-aws = "^2.0.1"
pip-tools = "^7.3.0"
psycopg2-binary = "^2.9.9"
python-dotenv = "^1.0.0"
redis = "^5.0.1"
requests = "^2.31.0"
tenacity = "^8.2.3"
whitenoise = "^6.6.0"

#[build-system]
#requires = ["poetry-core"]
#build-backend = "poetry.core.masonry.api"
