# Generated by Django 3.2.20 on 2023-09-18 11:29

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sampletable",
            name="sample_email",
            field=models.EmailField(max_length=256, null=True),
        ),
    ]
