# Generated by Django 4.2.11 on 2024-03-21 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_scheduledtask"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sampletable",
            old_name="sampleid",
            new_name="sample_id",
        ),
        migrations.AlterUniqueTogether(
            name="sampletable",
            unique_together={("sample_id", "sample_name")},
        ),
    ]
