version: 0.2

# env:
#   variables:
#     VERSION:  v0.27.0
#     INPUT_BUILDER: paketobuildpacks/builder:0.2.263-full
#     TAG: latest
#     APP_NAME: demodjango
#     LOG_LEVEL: DEBUG

    #PYTHON_VERSION: 3.9.*


phases:
#   install:
#     commands:
#       - curl -LO https://github.com/buildpacks/pack/releases/download/${VERSION}/pack-${VERSION}-linux.tgz
#       - tar xfz pack-${VERSION}-linux.tgz
#       - mv pack /usr/bin/
#       # - codebuild-breakpoint
#
  build:
    commands:
        - /work/build.sh
        - codebuild-breakpoint
#       #- aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${DOCKERREG}
#       - |
#         if [ -f "runtime.txt" ]; then
#           export PYTHON_VERSION=`cat runtime.txt |awk -F - '{print $2}'`
#           pack build ${APP_NAME}:${TAG} --builder ${INPUT_BUILDER} --env BP_LOG_LEVEL=${LOG_LEVEL} --env BP_CPYTHON_VERSION=${PYTHON_VERSION}
#         else
#           pack build ${APP_NAME}:${TAG} --builder ${INPUT_BUILDER} --env BP_LOG_LEVEL=${LOG_LEVEL}
#         fi
      #- docker tag ${APP_NAME}:${TAG} ${DOCKERREG}/uktrade/${APP_NAME}:${TAG}
      #- docker push ${DOCKERREG}/uktrade/${APP_NAME}:${TAG}
