name: Trufflehog scan

on: [push]

permissions: read-all

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@master
        with:
          scanArguments: " --no-verification --fail --exclude-paths=.trufflehogignore"
